### ISSUE TITLE
invalid DNA character in input k-mer

### ISSUE THREAD

**Issue by sarah872** [ctb/2020-long-read-assembly-decontam#1]
I got an error when running the `extract-matching-fragments.py`:
```
python extract-matching-fragments.py \
>               matches.sig $assembly \
>               --output-fragments matching-fragments.fa \
>               --matching-contigs matching-contigs.fa \
>               --nomatch-contigs nomatch-contigs.fa \
>               -F 2000
loaded 2 signatures total from matches.sig
aggregating matches...
...total hashes (incl not matching): 3118
outputting to: matching-fragments.fa
loading final-assembly.fasta...
Traceback (most recent call last): start 550000 - found 7 so far
  File "extract-matching-fragments.py", line 115, in <module>
    sys.exit(main())
  File "extract-matching-fragments.py", line 69, in main
    mh.add_sequence(seq)
  File "/home/user/py3-venv/lib/python3.7/site-packages/sourmash/_minhash.py", line 183, in add_sequence
    self._methodcall(lib.kmerminhash_add_sequence, to_bytes(sequence), force)
  File "/home/user/py3-venv/lib/python3.7/site-packages/sourmash/utils.py", line 25, in _methodcall
    return rustcall(func, self._get_objptr(), *args)
  File "/home/user/py3-venv/lib/python3.7/site-packages/sourmash/utils.py", line 78, in rustcall
    raise exc
ValueError: invalid DNA character in input k-mer: ATGGTTACCTCCTGAGTGATGCCCNNNNNNG
```

**Comment by ctb** [comment]
ooh thanks, fixed!

On Mon, Apr 13, 2020 at 09:51:13AM -0700, sarah872 wrote:
> I got an error when running the `extract-matching-fragments.py`:
> ```
> python extract-matching-fragments.py \
> >               matches.sig $assembly \
> >               --output-fragments matching-fragments.fa \
> >               --matching-contigs matching-contigs.fa \
> >               --nomatch-contigs nomatch-contigs.fa \
> >               -F 2000
> loaded 2 signatures total from matches.sig
> aggregating matches...
> ...total hashes (incl not matching): 3118
> outputting to: matching-fragments.fa
> loading final-assembly.fasta...
> Traceback (most recent call last): start 550000 - found 7 so far
>   File "extract-matching-fragments.py", line 115, in <module>
>     sys.exit(main())
>   File "extract-matching-fragments.py", line 69, in main
>     mh.add_sequence(seq)
>   File "/home/user/py3-venv/lib/python3.7/site-packages/sourmash/_minhash.py", line 183, in add_sequence
>     self._methodcall(lib.kmerminhash_add_sequence, to_bytes(sequence), force)
>   File "/home/user/py3-venv/lib/python3.7/site-packages/sourmash/utils.py", line 25, in _methodcall
>     return rustcall(func, self._get_objptr(), *args)
>   File "/home/user/py3-venv/lib/python3.7/site-packages/sourmash/utils.py", line 78, in rustcall
>     raise exc
> ValueError: invalid DNA character in input k-mer: ATGGTTACCTCCTGAGTGATGCCCNNNNNNG
> ```
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ctb/2020-long-read-assembly-decontam/issues/1
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by ctb** [comment]
fixed in 6ca9f44

**Comment by sarah872** [comment]
ha! that was quick. Thanks!

**Comment by ctb** [comment]
not my first time on that error!

let me know how it goes for you --

best,
--titus

**Comment by sarah872** [comment]
well, it's running without error :)
